### ISSUE TITLE
[BUG] ImportError: cannot import name 'shape' (Python 3.6)

### ISSUE THREAD

**Issue by zhenhouhong** [PennyLaneAI/pennylane#1922] opened 2021-11-22 10:51 UTC
### Expected behavior

Installed the newest version of pennylane (v0.19.0), try to run the noisy circuits example of https://pennylane.ai/qml/demos/tutorial_noisy_circuits.html .

### Actual behavior

Shows a error:
ImportError: cannot import name 'shape'

### Additional information

I check the github, found the pennylane/math/__init__.py didn't include the shape.
And I check the module code of math, seems it didn't has the shape function.

### System information

```shell
Ubuntu 18.04 x86_64 GNU/Linux, python3.6.9
```

### 

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment] 2021-11-22 11:00
Hi @zhenhouhong! Unfortunately, PennyLane no longer supports Python 3.6, which is the cause of this error --- dynamic module imports are only supported in Python 3.7 and above.

We recommend you upgrade to a newer Python version 🙂

**Comment by zhenhouhong** [comment] 2021-11-23 02:20
OK, thanks @josh146

**Comment by josh146** [comment] 2021-11-23 07:07
no worries @zhenhouhong --- I'll close this issue now. Feel free to open a new issue if you come across any bugs!

**Closed by josh146** 2021-11-23 07:07 UTC
