### ISSUE TITLE
Incorrect matrix for Tensors with unordered wires

### ISSUE THREAD

**Issue by trbromley** [PennyLaneAI/pennylane#591] opened 2020-04-16 15:47 UTC
The `matrix` attribute for PL's `Tensor` class can give an incorrect matrix when the observables used to specify the tensor are provided unordered according to the wires.

For example, consider the observable `IZ`. We can feed a wire-ordered list `[qml.Identity(wires=0), qml.PauliZ(wires=1)]` and a wire-unordered list `[qml.PauliZ(wires=1), qml.Identity(wires=0)]` to create the Tensor. The former gives the correct matrix, while the latter doesn't:
```python
>>> t1 = qml.operation.Tensor(*[qml.Identity(wires=0), qml.PauliZ(wires=1)])
>>> t2 = qml.operation.Tensor(*[qml.PauliZ(wires=1), qml.Identity(wires=0)])
>>> np.allclose(t1.matrix, t2.matrix)
False
```
In fact, the tensor `t2` from the wire-unordered list gives the matrix corresponding to `ZI`:
```python
>>> t3 = qml.operation.Tensor(*[qml.PauliZ(wires=0), qml.Identity(wires=1)])
>>> np.allclose(t3.matrix, t2.matrix)
True
```

This may be linked to https://github.com/XanaduAI/pennylane/issues/460.

**Comment by co9olguy** [comment] 2020-04-17 14:26
I lost track about whether there is a parent issue that gathers these things, but there are a number of open issues related to wire bookkeeping:

- https://github.com/XanaduAI/pennylane/issues/521
- https://github.com/XanaduAI/pennylane/issues/532
- https://github.com/XanaduAI/pennylane/issues/456
- https://github.com/XanaduAI/pennylane/issues/423

Be good to squash all these issues all at once

**Comment by mariaschuld** [comment] 2020-04-20 06:15
I will think about a new overall wire strategy this week, and will have these issues in mind...anyone keen to help out?

**Comment by josh146** [comment] 2020-04-20 06:17
I'm keen to help out!

**Comment by mariaschuld** [comment] 2020-07-23 15:17
Finally got back to this issue. 

The problem is the following: The tensor product does of course not commute, but after the wires refactor we cannot assume that a user's wire labels (in the example `0` and `1`, but could also be 'ancilla' and 'q1') tell the Tensor class about a "true" underlying order. As a consequence, we need to rely on the user of this function to order the local observables correctly. 

In short, calling
```
t = qml.operation.Tensor(qml.Identity(wires=1), qml.PauliZ(wires=0))
```
but wanting PennyLane to reorder the local observables is not expected user behaviour, and it's hard to flag such a case as wrong (what if the user just calls the first wire 1 and the second 0) on the level of the operation class. 
However, a user would typically call the signature advertised in the docs:
```
qml.Identity(wires=1) @ qml.PauliZ(wires=0)
```
where it should already feel like a wrong ordering, since @ is known as a non-commutative matrix multiplication.

We could in principle introduce a check in the qnode, which knows about the underlying "true" wire ordering of a device and should also have access to the original list of observables through `t.obs`...

**Comment by josh146** [comment] 2020-07-24 05:04
@mariaschuld, just to summarize your comment (and make sure I follow correctly): it is generally impossible with the new Wires refactor to tell if the order of the tensor products is monotonically increasing or not, so all we can hope to do it:

* Internally assume the provided tensor observables _are_ provided in order of increasing wires

**Comment by mariaschuld** [comment] 2020-07-24 08:00
Almost :) 

It depends on *where* you want to verify the order: In a qnode (i.e., if the tensor observable is encountered when executing a circuit) this is no problem, because the qnode has full information on a device's register and hence the order of the wire labels a user provides. But in the operator class itself this is not possible, at least not without passing information from a qnode somehow.

**Comment by mariaschuld** [comment] 2020-09-14 18:24
@co9olguy just a quick question: did the queuing refactor fix this? I remember you mentioning that this could be potentially obsolete after...

To make tensor observables have the wanted behaviour, the tensor product would have to happen in a context where the device is known.

**Comment by co9olguy** [comment] 2020-09-14 18:32
To my knowledge, this was not "actively" fixed during the queuing refactor. @josh146 or @antalszava might have more info about whether it was "accidentally" fixed though :laughing:

**Comment by josh146** [comment] 2020-09-15 02:55
I don't believe this is fixed, no. This requires code changes to the `Tensor` class directly.

I'm also not sure the best solution.

Perhaps we just assume that tensor product order explicitly defines the order of the operators (so the left-most operator is acting on the top-most wire)? Optionally, you can pass device wires to enforce some permutation?

**Comment by mariaschuld** [comment] 2020-09-15 11:26
Can't we delay the execution of the tensor product until we are in a context where we know what the wires are? Then everything would be well-defined and logical: the tensor observable only has a numerical representation once it is associated with a device.

**Comment by josh146** [comment] 2020-09-15 11:37
Oh, to be honest, I don't even think `Tensor.matrix` is _used_ anywhere, not even by plugins. It was simply provided as a convenience method for users to echo `qml.PauliX(0).matrix` etc.

**Comment by mariaschuld** [comment] 2020-09-21 19:43
After some discussion we are closing this bug report, since it is addressing an outdated logic that the ``Tensor`` class follows, producing non-intuitive behaviour. We will address necessary changes in an upcoming refactor that improves the behaviour of the ``Tensor`` class to only ever produce a matrix representation when called in the context of a device.

**Closed by mariaschuld** 2020-09-21 19:43 UTC
Labels: bug :bug:
