### ISSUE TITLE
Copy and deepcopy of a non-parametrized operation only references `op.matrix`

### ISSUE THREAD

**Issue by thisac** [PennyLaneAI/pennylane#1415] opened 2021-06-17 22:30 UTC
#### Issue description

When copying a non-parametrized operation, e.g. CNOT, the matrix is only copied as a reference. This is the case when using both `copy.copy` and `copy.deepcopy`. The following:

```python
import pennylane as qml
import copy

op = qml.CNOT(wires=[0,1])
op2 = copy.copy(op)
op3 = copy.deepcopy(op)

print("Before:")
print(op2.matrix)
print(op3.matrix)

op.matrix[0, 0] = 9

print("\nAfter:")
print(op2.matrix)
print(op3.matrix)
```
outputs:
```out
Before:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]

After:
[[9 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
[[9 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
```

* *Expected behavior:* (What you expect to happen)
I would expect at least deepcopy to make a deep copy of all the internal data.

* *Actual behavior:* (What actually happens)
Only references are being made to the internally saved matrix.

* *Reproduces how often:* (What percentage of the time does it reproduce?)
Every time

**Comment by josh146** [comment] 2021-06-18 06:39
@thisac I believe this was intentional, however for the life of me, I cannot remember the reason 🤔 

Perhaps to avoid having to copy large numpy arrays in memory?

**Comment by co9olguy** [comment] 2021-06-18 12:51
I seem to remember that things also just did not work if a deep copy was made. Something to do with the dependency graph for tracking differentiation maybe?

**Comment by josh146** [comment] 2021-07-06 09:49
> I seem to remember that things also just did not work if a deep copy was made. Something to do with the dependency graph for tracking differentiation maybe?

Yes, this could be the case. I'm tempted to label this as 'won't fix', because:

- The current behaviour is expected behaviour. If it is surprising, it should be better documented in the developer documentation.
- I'm unsure there is a use-case where copying the operations requires parameters to be copied. @thisac correct me if I'm wrong - was there an issue in a PR that uncovered this issue, or was it just opened as it was found to be unexpected?

**Comment by thisac** [comment] 2021-07-07 14:37
> was there an issue in a PR that uncovered this issue, or was it just opened as it was found to be unexpected?

This is not connected to any issues. I found it slightly unexpected, or at least potentially misleading

> I don't think we should keep open issues labeled as bugs if there is no intention to create a 'fix'.

I fully agree with this! I have no strong feelings about this at all, but I'm thinking that it could lead to confusing bugs (although I can't really see that this would happen often). Would it be good to add a warning if a user attempts to deepcopy an operation? Especially if other things might not work as well when doing that?

**Comment by josh146** [comment] 2021-07-07 15:10
> Would it be good to add a warning if a user attempts to deepcopy an operation? Especially if other things might not work as well when doing that?

I lean towards not, since we can't properly distinguish between PL itself performing deepcopies or users performing deepcopies. The core itself might create deepcopies, which would result in a cascade of warnings appearing to unexpected users 😆

**Comment by albi3ro** [comment] 2021-07-07 15:29
For the CNOT case, the matrix is a class variable, so even independent objects have correlated `matrix` values:

```
op1 = qml.CNOT(wires=(0,1))
op2 = qml.CNOT(wires=(2,3))
op1.matrix[0,0] = 9
print(op1.matrix)
print(op2.matrix)
```

```
array([[9, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])
array([[9, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])
```

**Comment by albi3ro** [comment] 2023-09-22 19:49
There no longer is an `Operator.matrix` property, so this is no longer an issue.

**Closed by albi3ro** 2023-09-22 19:49 UTC
Labels: wontfix :see_no_evil:
