### ISSUE TITLE
I hope pennylane-qsharp can be updated

### ISSUE THREAD

**Issue by hauson-fan** [PennyLaneAI/pennylane#920] opened 2020-11-22 06:17 UTC
#### Before posting an issue

Search existing GitHub issues to make sure the issue does not already exist:
https://github.com/xanaduai/pennylane/issues

If posting a PennyLane issue, delete everything above the dashed line, and fill
in the template.

If making a feature request, delete the following template and describe, in detail,
the feature and why it is needed.

For general technical details check out our documentation:
https://pennylane.readthedocs.io

-------------------------------------------------------------------------------------------------------------

#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* code by pennylane-qsharp can run successfully

* *Actual behavior:* QDK has some errors

* *Reproduces how often:* Always

* *System information:* 
```
Name: PennyLane
Version: 0.12.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: d:\users\asus\anaconda3\lib\site-packages
Requires: scipy, numpy, appdirs, networkx, autograd, toml, semantic-version
Required-by: PennyLane-qsharp
Platform info:           Windows-10-10.0.18362-SP0
Python version:          3.8.3
Numpy version:           1.19.2
Scipy version:           1.5.2
Installed devices:
- default.gaussian (PennyLane-0.12.0)
- default.mixed (PennyLane-0.12.0)
- default.qubit (PennyLane-0.12.0)
- default.qubit.autograd (PennyLane-0.12.0)
- default.qubit.tf (PennyLane-0.12.0)
- default.tensor (PennyLane-0.12.0)
- default.tensor.tf (PennyLane-0.12.0)
- microsoft.QuantumSimulator (PennyLane-qsharp-0.8.0)
```

#### Source code and tracebacks

```Python
dev = qml.device('microsoft.QuantumSimulator', wires=2)

@qml.qnode(dev)
def circuit(x, y, z):
    qml.RZ(z, wires=[0])
    qml.RY(y, wires=[0])
    qml.RX(x, wires=[0])
    qml.CNOT(wires=[0, 1])
    return qml.expval(qml.PauliZ(wires=1))

circuit(0.2, 0.1, 0.3)
```

```
e:\snippet_.qs(9,19): error QS3101: Syntax error in expression.
e:\snippet_.qs(10,23): error QS3101: Syntax error in expression.
e:\snippet_.qs(11,23): error QS3101: Syntax error in expression.
e:\snippet_.qs(12,38): error QS3101: Syntax error in expression.
e:\snippet_.qs(12,20): error QS3101: Syntax error in expression.
e:\snippet_.qs(15,56): error QS3101: Syntax error in expression.
e:\snippet_.qs(15,29): error QS3101: Syntax error in expression.
```

**Comment by co9olguy** [comment] 2020-11-23 14:27
Hi @hauson-fan, thanks for making the issue! 
To help us understand the bug, can you please post the output of running `qml.about()`?

**Comment by hauson-fan** [comment] 2020-12-06 05:32
@co9olguy 
Name: PennyLane
Version: 0.12.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: None
Author-email: None
License: Apache License 2.0
Location: d:\users\asus\anaconda3\lib\site-packages
Requires: scipy, numpy, appdirs, networkx, autograd, toml, semantic-version
Required-by: PennyLane-qsharp
Platform info:           Windows-10-10.0.18362-SP0
Python version:          3.8.3
Numpy version:           1.19.2
Scipy version:           1.5.2
Installed devices:
- default.gaussian (PennyLane-0.12.0)
- default.mixed (PennyLane-0.12.0)
- default.qubit (PennyLane-0.12.0)
- default.qubit.autograd (PennyLane-0.12.0)
- default.qubit.tf (PennyLane-0.12.0)
- default.tensor (PennyLane-0.12.0)
- default.tensor.tf (PennyLane-0.12.0)
- microsoft.QuantumSimulator (PennyLane-qsharp-0.8.0)

**Comment by josh146** [comment] 2020-12-09 16:53
Thanks @hauson-fan! Could you also let us know the version of the Microsoft QDK you are using?

**Comment by hauson-fan** [comment] 2020-12-11 12:47
@josh146 
version 0.14.2011120240.

**Comment by trbromley** [comment] 2020-12-18 22:10
Thanks @hauson-fan for updating us with this and it's on our to-do list to check out.

**Comment by co9olguy** [comment] 2020-12-24 18:12
Hi @hauson-fan,

I spent some time today setting up the Microsoft QDK on my Windows machine (I normally work in Linux) and duplicating your python installations. I was able to reproduce the error you mentioned above. Notably, I also have the text of the Python exception, which should help us pinpoint the error better:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Coolguy\AppData\Local\Programs\Python\Python38\lib\site-packages\pennylane\interfaces\autograd.py", line 69, in __call__
    return self.evaluate(args, kwargs)
  File "C:\Users\Coolguy\AppData\Local\Programs\Python\Python38\lib\site-packages\autograd\tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "C:\Users\Coolguy\AppData\Local\Programs\Python\Python38\lib\site-packages\pennylane\qnodes\base.py", line 828, in evaluate
    ret = self.device.execute(
  File "C:\Users\Coolguy\AppData\Local\Programs\Python\Python38\lib\site-packages\pennylane\_device.py", line 279, in execute
    self.post_apply()
  File "C:\Users\Coolguy\AppData\Local\Programs\Python\Python38\lib\site-packages\pennylane_qsharp\device.py", line 138, in post_apply
    self.qs = qsharp.compile(self._source_code)
  File "C:\Users\Coolguy\AppData\Local\Programs\Python\Python38\lib\site-packages\qsharp\__init__.py", line 58, in compile
    ops = [
TypeError: 'NoneType' object is not iterable
```

@josh146 you wrote this plugin, any initial thoughts? Perhaps the `Wires` object? 🤔 

```

**Comment by co9olguy** [comment] 2020-12-24 18:17
For reference, here is what the pre-compiled QSharp code looks like for this PennyLane circuit:
```
open Microsoft.Quantum.Convert;
open Microsoft.Quantum.Measurement;

operation Program () : Bool[] {
    mutable resultArray = new Result[2];
    using (q = Qubit[2]) {
        // operations
        Rz(0.3, q[<Wires = [0]>]);
            Rx(0.1, q[<Wires = [0]>]);
            Ry(0.2, q[<Wires = [0]>]);
            CNOT(q[<Wires = [0]>], q[<Wires = [1]>]);

        // measurements
        set resultArray w/= <Wires = [1]> <- MResetZ(q[<Wires = [1]>]);

        // reset all qubits
        ResetAll(q);
    }
    return ResultArrayAsBoolArray(resultArray);
}
```

**Comment by co9olguy** [comment] 2020-12-24 18:26
Certainly looks like the client.compile function in qsharp is the point of failure. Might be because the program above is no longer correct due to a breaking change in the syntax?

**Comment by josh146** [comment] 2020-12-25 03:30
@co9olguy yep this is very much a Wires refactor issue! The operations are being serialized as 

```python
Rx(0.1, q[<Wires = [0]>]);
```
when they should be serialized as 

```python
Rx(0.1, q[0]);
```

This should be an easy fix, should be as simple as changing `wires` to `wires.tolist()` somewhere within the plugin.

**Comment by josh146** [comment] 2020-12-28 14:45
That's odd, it looks like this is already being done in the plugin 🤔 

https://github.com/PennyLaneAI/PennyLane-qsharp/blob/master/pennylane_qsharp/device.py#L130

**Comment by josh146** [comment] 2021-01-04 04:06
I am attempting to update the PL-Q# plugin here: https://github.com/PennyLaneAI/PennyLane-qsharp/pull/13

**Comment by antalszava** [comment] 2021-01-05 19:20
Hi @hauson-fan, we had a further look and as @josh146 pointed out the issue should be resolved by using the latest `master` branch of the plugin. The open PR further resolves other issues and runs PennyLane device tests.

Until these changes are released a workaround can be to use the `master` branch version of the plugin.

**Closed** 2021-03-18 06:40 UTC
