### ISSUE TITLE
Problem with non-standard shift differentiable gates in decompositions

### ISSUE THREAD

**Issue by cvjjm** [PennyLaneAI/pennylane#1037] opened 2021-01-25 15:08 UTC
I have run across a problem when using some of the four term shift differentiable gates (such as `CRY`) in decompositions of other custom gates. It is hard to provide a good minimal non-working example, but I have been able to work out the following:

When I use `CRY` in de decomposition of a gate that is itself shirt differentiable, then the jacobian on devices no supporting this gate natively (i.e., using the decomposition) is wrong (it differs from the finite difference gradient). If instead I insert `CRY.decomposition()` into the decomposition of my custom gate, which should really do exactly the same thing, then the jacobian is correct (i.e., it matches the finite difference jaccobian on both a device that uses the decomposition and on on that does support the gate natively).

My minimal example are two gates that, I think, should behave exactly identical on `"default.qubit"`, but they are giving different jacobians:
```
class Test1(Operation):
    num_params = 1
    num_wires = 2
    par_domain = "R"
    grad_method = "A"
    grad_recipe = four_term_grad_recipe

    @staticmethod
    def _matrix(*params):
        theta = params[0]
        c = np.cos(theta / 2)
        s = np.sin(theta / 2)
        return np.array(
            [
                [1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 1, 0],
                [0, 0, 0, 1],
            ]
        )

    @staticmethod
    def decomposition(theta, wires):
        decomp_ops = \
            qml.CRY.decomposition(-theta / 2, wires=wires) + \
            qml.CRY.decomposition(theta / 2, wires=wires)
        return decomp_ops

class Test2(Operation):
    num_params = 1
    num_wires = 2
    par_domain = "R"
    grad_method = "A"
    grad_recipe = four_term_grad_recipe

    @staticmethod
    def _matrix(*params):
        theta = params[0]
        c = np.cos(theta / 2)
        s = np.sin(theta / 2)
        return np.array(
            [
                [1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 1, 0],
                [0, 0, 0, 1],
            ]
        )

    @staticmethod
    def decomposition(theta, wires):
        decomp_ops = [
            qml.CRY(-theta / 2, wires=wires),
            qml.CRY(theta / 2, wires=wires),
        ]
        return decomp_ops
```
The fact that these gates are also both the identity, i.e., doing nothing, has nothing to do with this problem. I just found it hard produce a "minimal" example that does not have this property.

Gate `Test1` is behaving correctly and giving a trivial jacobian, whereas `Test2` yields a non-zero jacobian.

You can see that the only difference between the two gates is that in Test2 I am using `CRY` in the `decomp_list`, whereas in Test1 I am concatenating the lists I get from `CRY.decomposition()`.

**Comment by josh146** [comment] 2021-01-25 15:10
Hi @cvjjm! Thanks for catching this - do you have a minimal bit of code you are using for the QNode and corresponding Jacobian computation?

**Comment by cvjjm** [comment] 2021-01-25 16:20
I was using this one for example with `gate` equal to the gates above:
```
    dev = qml.device("default.qubit")
    @qml.qnode(dev)
    def circuit1(params):
        for wire in range(gate.num_wires):
            qml.Rot(*prep_params[wire], wires=wire)
        gate(*params, wires=list(range(gate.num_wires)))
        for wire in range(gate.num_wires):
            qml.Rot(*prep_params[wire], wires=wire)
        return qml.probs(range(gate.num_wires))
```
But really any circuit that tests the jacobian on a non-trivial state should show that behavior.

**Comment by mariaschuld** [comment] 2021-01-26 08:34
Thanks @cvjjm, we will look into this!

**Comment by mariaschuld** [comment] 2021-01-26 14:42
Sorry, @cvjjm, but I just cannot reproduce your issue. Could you please post a minimal working example? For instance, in the two code pieces you posted things like `prep_params` and `four_term_grad_recipe` are not defined. 

Also, did you notice that your matrix representing the gate is the identity? The output of the circuit should therefore independent of the input. Maybe if you use decompositions, this bug simply gets bypassed?

**Comment by cvjjm** [comment] 2021-01-27 07:51
Apologies for not making the effort of submitting a full non-working example right away. I thought it should be easy to reproduce the behavior by running the PennyLane gate tests over the two custom gates. I provide a full demonstration of the problem below.

Please note that as the gate's decompositions do the same rotation forward and then backward, the identity matrix is in fact correct, but the content of `_matrix()` is also completely irrelevant, as it is never called (I now make that apparent in the full example). The gates `Test1` and `Test2` are nor supported by `'default.qubit'` and thus decomposed. As I wrote above, I originally stumbled across this problem with a more complicated (but actually four-term differentiable) gate that is not the identity. 

A full demonstration of the problem is the following:
```
import pennylane as qml
import numpy as np
from pennylane.operation import Operation
from pennylane.ops.qubit import four_term_grad_recipe


class Test1(Operation):
    num_params = 1
    num_wires = 2
    par_domain = "R"
    grad_method = "A"
    grad_recipe = four_term_grad_recipe

    @staticmethod
    def _matrix(*params):
        raise NotImplementedError()

    @staticmethod
    def decomposition(theta, wires):
        decomp_ops = \
            qml.CRY.decomposition(-theta / 2, wires=wires) + \
            qml.CRY.decomposition(theta / 2, wires=wires)
        return decomp_ops

class Test2(Operation):
    num_params = 1
    num_wires = 2
    par_domain = "R"
    grad_method = "A"
    grad_recipe = four_term_grad_recipe

    @staticmethod
    def _matrix(*params):
        raise NotImplementedError()

    @staticmethod
    def decomposition(theta, wires):
        decomp_ops = [
            qml.CRY(-theta / 2, wires=wires),
            qml.CRY(theta / 2, wires=wires),
        ]
        return decomp_ops

np.random.seed(42)
prep_params = np.random.rand(Test1.num_wires, 3)
dev = qml.device("default.qubit", wires=Test1.num_wires)

@qml.qnode(dev)
def circuit1(params):
    for wire in range(Test1.num_wires):
        qml.Rot(*prep_params[wire], wires=wire)
    Test1(*params, wires=list(range(Test1.num_wires)))
    for wire in range(Test1.num_wires):
        qml.Rot(*prep_params[wire], wires=wire)
    return qml.probs(range(Test1.num_wires))

@qml.qnode(dev)
def circuit2(params):
    for wire in range(Test2.num_wires):
        qml.Rot(*prep_params[wire], wires=wire)
    Test2(*params, wires=list(range(Test2.num_wires)))
    for wire in range(Test2.num_wires):
        qml.Rot(*prep_params[wire], wires=wire)
    return qml.probs(range(Test2.num_wires))


test_params = np.random.rand(Test1.num_params)

jac_dev1 = np.array(qml.jacobian(circuit1, argnum=0)(test_params))
jac_dev2 = np.array(qml.jacobian(circuit2, argnum=0)(test_params))
print(jac_dev1)
print(jac_dev2)
```
When I run this I get
```
[[ 1.38777878e-17]
 [-4.85722573e-17]
 [ 2.77555756e-17]
 [-2.42861287e-17]]
[[ 2.30769166e-03]
 [ 6.87303984e-04]
 [-2.38524478e-18]
 [ 1.69406589e-21]]
```
The first gradient is correct. The gate is trivial and thus it's gradient should be zero - and it is up to machine precision. The second gradient is wrong. But the two gates should be exactly identical because they have the same decomposition. The only difference is that Test1 is decomposed all the way into `RY`s and `CX`s whereas `Test2` is decomposed into a circuit of `CRY`s, as can be verified by `.draw()`ing the circuits after execution.

**Comment by mariaschuld** [comment] 2021-01-28 08:20
Ah thanks, that will help a lot! Will get back to you!

**Comment by antalszava** [comment] 2021-01-28 22:23
Hi @cvjjm, thank you so much for the detailed description and the full example!

Today we merged in a major update to PennyLane (#1040, making the so called "tape mode" default). It seems that this behaviour is solved in the new version of Pennylane. Nonetheless, I could indeed reproduce your results in non-tape mode (running `qml.disable_tape()`).

Let me know however if there would be some affected cases even with the new updates.

**Comment by cvjjm** [comment] 2021-01-29 11:43
Good to hear that you can reproduce the problem and even better that it is now solved in tape mode!

I think it would still be good to get it fixed in the legacy mode. 

Is there an estimate of how much performance overhead tape mode incurs? This will be critical for many of our use cases.

**Comment by josh146** [comment] 2021-01-29 12:36
@cvjjm we wrote tape mode to attempt to remove a lot of the overhead that was occurring in legacy mode 🙂  This new mode completely removes the `Variable` class, and use of our recursive `flatten` and `unflatten` functions, which were a large source of overhead. So in almost all cases, the new core of PennyLane should be faster.

**Comment by cvjjm** [comment] 2021-01-29 13:23
Nice! Looking forward to playing with it :-)

**Comment by antalszava** [comment] 2021-01-29 16:51
Closing this for now in favour of using tape mode (can be reopened if needed).

**Closed by antalszava** 2021-01-29 16:51 UTC
Labels: bug :bug:

**Comment by cvjjm** [comment] 2021-02-25 10:45
Just wanted to report that this bug is indeed "fixed" in the current master with tape mode enabled.

With tape mode disabled and parameter shift gradients are enforced the gradient still comes out wrong, as can be verfied by running:
```
import pennylane as qml
import numpy as np
from pennylane.operation import Operation
from pennylane.ops.qubit import four_term_grad_recipe

qml.disable_tape()

class Test1(Operation):
    num_params = 1
    num_wires = 2
    par_domain = "R"
    grad_method = "A"
    grad_recipe = four_term_grad_recipe

    @staticmethod
    def _matrix(*params):
        raise NotImplementedError()

    @staticmethod
    def decomposition(theta, wires):
        decomp_ops = \
            qml.CRY.decomposition(-theta / 2, wires=wires) + \
            qml.CRY.decomposition(theta / 2, wires=wires)
        return decomp_ops

class Test2(Operation):
    num_params = 1
    num_wires = 2
    par_domain = "R"
    grad_method = "A"
    grad_recipe = four_term_grad_recipe

    @staticmethod
    def _matrix(*params):
        raise NotImplementedError()

    @staticmethod
    def decomposition(theta, wires):
        decomp_ops = [
            qml.CRY(-theta / 2, wires=wires),
            qml.CRY(theta / 2, wires=wires),
        ]
        return decomp_ops

np.random.seed(42)
prep_params = np.random.rand(Test1.num_wires, 3)
dev = qml.device("default.qubit", wires=Test1.num_wires)

@qml.qnode(dev, diff_method='parameter-shift')
def circuit1(params):
    for wire in range(Test1.num_wires):
        qml.Rot(*prep_params[wire], wires=wire)
    Test1(*params, wires=list(range(Test1.num_wires)))
    for wire in range(Test1.num_wires):
        qml.Rot(*prep_params[wire], wires=wire)
    return qml.probs(range(Test1.num_wires))

@qml.qnode(dev, diff_method='parameter-shift')
def circuit2(params):
    for wire in range(Test2.num_wires):
        qml.Rot(*prep_params[wire], wires=wire)
    Test2(*params, wires=list(range(Test2.num_wires)))
    for wire in range(Test2.num_wires):
        qml.Rot(*prep_params[wire], wires=wire)
    return qml.probs(range(Test2.num_wires))


test_params = np.random.rand(Test1.num_params)

jac_dev1 = np.array(qml.jacobian(circuit1, argnum=0)(test_params))
jac_dev2 = np.array(qml.jacobian(circuit2, argnum=0)(test_params))
print(jac_dev1)
print(jac_dev2)
```

**Comment by josh146** [comment] 2021-02-25 11:00
Great to hear @cvjjm! I wonder what the original bug was... we must have inadvertently solved it while re-writing the core of PennyLane 🤔

**Comment by cvjjm** [comment] 2021-02-25 11:08
Well, the bug is still there in non tape mode. So tape mode must be doing something different that is relevant here.
