### ISSUE TITLE
[BUG]qnode execution on simulators slows down with increasing commuting Hamiltonian terms

### ISSUE THREAD

**Issue by duanyh12** [PennyLaneAI/pennylane#2706] opened 2022-06-14 03:15 UTC
### Expected behavior

With `compute_grouping` I would expect the following two qnodes, `circuit()` and `circuit2()`, to have similar execution time. 
```python
import pennylane as qml
from pennylane import numpy as np
import time

n_qubits = 15

H_quad = 0 * qml.PauliZ(0)
for i in range(n_qubits):
    for j in range(i + 1, n_qubits):
        H_quad += qml.PauliZ(i) @ qml.PauliZ(j)
H_quad.compute_grouping()

H_lin = 0 * qml.PauliZ(0)
for i in range(n_qubits):
    H_lin += qml.PauliZ(i)
H_lin.compute_grouping()

dev = qml.device("lightning.qubit", wires=n_qubits, shots=1000)
@qml.qnode(dev)
def circuit():
    for w in range(n_qubits):
        qml.Hadamard(wires=w)
    return qml.expval(H_quad)

@qml.qnode(dev)
def circuit2():
    for w in range(n_qubits):
        qml.Hadamard(wires=w)
    return qml.expval(H_lin)


start = time.time()
circuit()
end = time.time()
print(f"qnode with quadratic terms: {end - start}s")

start = time.time()
circuit2()
end = time.time()
print(f"qnode with linear terms: {end - start}s")
```

### Actual behavior

The qnode with quadratic terms executes significantly slower. Printed result from the code above:
```
qnode with quadratic terms: 0.8156991004943848s
qnode with linear terms: 0.004673004150390625s
```

### Additional information

The observation holds for both `default.qubit` and `lightning.qubit`.

### System information

```shell
Name: PennyLane
Version: 0.22.0
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/ec2-user/anaconda3/envs/Braket/lib/python3.7/site-packages
Requires: semantic-version, autograd, appdirs, numpy, autoray, pennylane-lightning, scipy, toml, cachetools, networkx, retworkx
Required-by: PennyLane-Qchem, PennyLane-Lightning, amazon-braket-pennylane-plugin
Platform info:           Linux-4.14.252-131.483.amzn1.x86_64-x86_64-with-glibc2.17
Python version:          3.7.13
Numpy version:           1.19.2
Scipy version:           1.5.2
Installed devices:
- default.gaussian (PennyLane-0.22.0)
- default.mixed (PennyLane-0.22.0)
- default.qubit (PennyLane-0.22.0)
- default.qubit.autograd (PennyLane-0.22.0)
- default.qubit.jax (PennyLane-0.22.0)
- default.qubit.tf (PennyLane-0.22.0)
- default.qubit.torch (PennyLane-0.22.0)
- lightning.qubit (PennyLane-Lightning-0.23.0)
- braket.aws.qubit (amazon-braket-pennylane-plugin-1.6.5)
- braket.local.qubit (amazon-braket-pennylane-plugin-1.6.5)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by mlxd** [comment] 2022-06-14 21:34
Hi @duanyh12 
I am currently looking into this, and can confirm the runtimes you show for v0.23. One thing I observed was the main/master branch for both PennyLane and PennyLane Lightning seem to demonstrate this issue is not showing the same runtimes as presented, as well the release candidates for the upcoming release v0.24. I think whatever changes were causing this are likely fixed in the coming release.

```bash
quadratic,0.039054155349731445s
quadratic,0.0352168083190918s
quadratic,0.03233790397644043s
quadratic,0.03778982162475586s
quadratic,0.032090187072753906s
quadratic,0.03257942199707031s
quadratic,0.03229784965515137s
quadratic,0.032037973403930664s
quadratic,0.03827476501464844s
quadratic,0.032161712646484375s

linear,0.0041425228118896484s
linear,0.003221273422241211s
linear,0.0032536983489990234s
linear,0.0036516189575195312s
linear,0.005267143249511719s
linear,0.0032651424407958984s
linear,0.003587007522583008s
linear,0.0033309459686279297s
linear,0.003934383392333984s
linear,0.003267526626586914s
```

**Comment by duanyh12** [comment] 2022-06-15 01:59
Hey Lee @mlxd . Confirming that I can reproduce your observation by simply upgrading pennylane from 0.22.0 to the current main branch.  That's good news.

Then I proceeded to the original example where I detected this issue to double check. This is a QAOA max cut example with a fully connected graph. Here I will compare the qnode execution time for the following expectation values:

1. max cut problem Hamiltonian
2. Hamiltonian with all quadratic terms
3. Hamiltonian with all linear terms

```python
import pennylane as qml
import networkx as nx
from pennylane import qaoa
from pennylane import numpy as np
import time

nodes = n_qubits = 20
edges = nodes * (nodes - 1) / 2
seed = 1

g = nx.gnm_random_graph(nodes, edges, seed=seed)
cost_h, mixer_h = qaoa.maxcut(g)

depth = 2
dev = qml.device("lightning.qubit", wires=n_qubits, shots=1000)
def qaoa_layer(gamma, alpha):
    qaoa.cost_layer(gamma, cost_h)
    qaoa.mixer_layer(alpha, mixer_h)
    
def qaoa_circuit(params, n_qubits, depth):
    #initalizing all qubits into +X eigenstate. 
    for w in range(n_qubits):
        qml.Hadamard(wires=w)
    gammas = params[0]
    alphas = params[1]
    #stacking building blocks for depth times.
    qml.layer(qaoa_layer, depth, gammas, alphas)
    
@qml.qnode(dev)
def cost_function(params):
    qaoa_circuit(params, n_qubits, depth)
    return qml.expval(cost_h) 

H_quad = 0 * qml.PauliZ(0)
for i in range(n_qubits):
    for j in range(i + 1, n_qubits):
        H_quad += qml.PauliZ(i) @ qml.PauliZ(j)
H_quad.compute_grouping()
@qml.qnode(dev)
def cost_function2(params):
    qaoa_circuit(params, n_qubits, depth)
    return qml.expval(H_quad)

H_lin = 0 * qml.PauliZ(0)
for i in range(n_qubits):
    H_lin += qml.PauliZ(i)
H_lin.compute_grouping()
@qml.qnode(dev)
def cost_function3(params):
    qaoa_circuit(params, n_qubits, depth)
    return qml.expval(H_lin)

params_init = 2 * np.pi * (np.random.rand(2, depth) - 0.5) 

start = time.time()
cost_function(params_init)
end = time.time()
print(f"qnode with QAOA loss: {end - start}s")

start = time.time()
cost_function2(params_init)
end = time.time()
print(f"qnode with all quadratic terms: {end - start}s")

start = time.time()
cost_function3(params_init)
end = time.time()
print(f"qnode with all linear terms: {end - start}s")
```
The result goes:
```
qnode with QAOA loss: 2.7502851486206055s
qnode with all quadratic terms: 1.5888128280639648s
qnode with all linear terms: 1.4632782936096191s
```
Quadratic qnode runs as fast as the linear qnode, and this confirms the issue is gone. But any hint why QAOA qnode is 2X slower? In this case the QAOA `cost_h` is pretty much just the `H_quad`, with a numerical factor. 

Another trivial thing: if I do `H_quad.wires`, I will get `<Wires = [0]>`. This seems to be related how I am defining this Hamiltonian (adding terms from the initial one on wire 0), but it is a bit counter-intuitive.

**Comment by Jaybsoni** [comment] 2022-06-15 20:54
Hi @duanyh12, 

Thanks for the question, there are two things going on here: 

1. The difference between the QAOA hamiltonian and the Quadratic hamiltonian is the presence of a term `-95.0 * qml.Identity(0)`. I am still investigating to see why a single term causes such a massive performance degradation. My hunch is that we have some logic which checks if all operations are off the same type (i.e all `PauliZ`) in which case we skip some validation checks and jump straight to computation. But I will provide more information once I track down the root cause. 

2. The wires not showing up is due to a bug in the `__iadd__()` method of the `Hamiltonian` class which forgets to update the wires when doing in place addition. In general we are moving away from in place computations in PennyLane. I will open a PR shortly to fix this issue. Alternatively you can update your code with: 
`H_quad = H_quad + qml.PauliZ(i) @ qml.PauliZ(j)`  instead of `H_quad += qml.PauliZ(i) @ qml.PauliZ(j)`

cheers,

**Comment by duanyh12** [comment] 2022-06-15 21:32
@Jaybsoni Hi Jay. Thanks for investigating. For 1, I am even wondering if resolving this issue could improve the overall QAOA ansatz layer execution efficiency (not limited to the measurement). Keep me posted!

**Comment by Jaybsoni** [comment] 2022-06-17 20:20
@duanyh12, 

The cause of this seems to be more elusive than I thought. I found one potential source in the way we sample (in `qml._qubit_device.py`) but this did not improve the computational run time significantly. I will come back to this next week. Thanks for your patience !

**Comment by Jaybsoni** [comment] 2022-06-23 06:25
@duanyh12, 

Thanks for your patience! We (@mlxd and I) were finally able to track down the source of the slow down. It turns out that we had recently added some logic which checks if a PauliWord (in this case you Hamiltonian) is made up of the same type of operator. In this special case the logic could skip checking for qubit-wise commutativity and just `return True`. 

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/21964864/175229182-ed9824ec-ec28-43cd-9cb6-a3cf31099125.png">

In the code block on the left you can see that I commented out the section of code responsible for the this special case check. In the terminal output on the right, you can see that the `final time:`  is ~1.5 sec for both the mixed term case and the all PauliZ case once the section of code was commented out. Contrasting this with the speed up of ~1sec we get from including this special check in the `pre_change` run. 

Since ultimately this code is responsible for a speed-up rather then a slow down, we don't plan on changing anything here. Let me know if you have any other questions. I will be marking this issue as resolved. 

Cheers,

**Closed by Jaybsoni** 2022-06-23 06:25 UTC
Labels: bug :bug:

**Comment by duanyh12** [comment] 2022-06-24 06:51
Hey Jay @Jaybsoni. My apologies for the delay in response, and I really appreciate the deep dive. Your explanation is super clear!

Here just intuitively speaking, I feel adding identities leading to more checks and therefore reduced performance is a strange thing, as identities commute with any paulis. I wonder if it is possible that in this line ( https://github.com/PennyLaneAI/pennylane/blob/master/pennylane/grouping/transformations.py#L146 ) we change the condition to be something like (pseudocode):
`all(first_pauli_name == sub_word_name or (sub_word_name is identity) for sub_word_name in pauli_word.name)`
If the former condition holds, the latter one will not be checked, so there will be no overhead added. Yet when the former condition is not satisfied, the latter one can capture identity cases. My assumption is that identities really are trivial cases for any commutation checks? Let me know if my words make  any sense!

**Comment by Jaybsoni** [comment] 2022-06-28 21:21
Hi @duanyh12, 

Great suggestion! Yes, Identity operators will commute with every other observable so we shouldn't have to worry about them in these qwc checks. I think we can actually further build on this idea to get an even better boost in performance. Here is a new [feature request](https://github.com/PennyLaneAI/pennylane/issues/2788) I have created where we can discuss how to further improve the performance
