### ISSUE TITLE
[BUG] from Pennylane import numpy produces all numpy arrays with requires_grad = True

### ISSUE THREAD

**Issue by sophchoe** [PennyLaneAI/pennylane#1693] opened 2021-09-27 23:08 UTC
### Expected behavior

A dataset numpy array to be just an array

### Actual behavior

It produces an array with [[],... requires_grad = True]

### System information

```shell
MacOS, Python 3.8.5
```

### 

- [X] I have searched exisisting GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment] 2021-09-28 06:55
Hi @sophchoe! Thanks for reporting this.

This is currently intentional behaviour --- all NumPy arrays created with the PL version of NumPy will default to having `requires_grad=True` by default. If you would like to change this, you can specify `requires_grad=False`:

```python
from pennylane import numpy as np

data = np.array([0.2 0.34], requires_grad=False)
```

In a future release of PennyLane, we are likely to change this, and switch to using `requires_grad=False` by default. However, this is not currently scheduled.

**Comment by josh146** [comment] 2021-09-28 06:56
As this is intended behaviour @sophchoe, I will close this bug report. Let me know if the code snippet above works for you! 

And if you notice any other bugs or issues, don't hesitate to open another issue 🙂

**Closed by josh146** 2021-09-28 06:56 UTC
Labels: bug :bug:
