### ISSUE TITLE
[BUG] Incorrect optimal sector in qubit tapering

### ISSUE THREAD

**Issue by Jonas-Jaeger** [PennyLaneAI/pennylane#5016] opened 2024-01-08 10:04 UTC
### Expected behavior

In _Qubit Tapering_ [2], the method `qml.qchem.optimal_sector` [1,3] should deliver the optimal eigenvalues for non-trivially tapered qubits such that the lowest eigenvalue of the tapered hamiltonian still matches the lowest eigenvalue of the untapered hamiltonian. 

For the example using HeH+ in the pennylane tutorial/demo [1] (https://pennylane.ai/qml/demos/tutorial_qubit_tapering/) it is expected that `optimal_sector` returns a sector (i.e., `[-1, +1]` or `[+1, -1]`) such that the tapered 4-qubit hamiltonian contains the lowest eigenvalue of the original hamiltonian, i.e., -3.12541987 

**Screenshot:**
![Screenshot 2024-01-08 102957](https://github.com/PennyLaneAI/pennylane/assets/34666257/a82d2343-9d3a-4990-a2c4-145f158fe006)

#### References:

1. https://pennylane.ai/qml/demos/tutorial_qubit_tapering/
2. Bravyi, Sergey, Jay M. Gambetta, Antonio Mezzacapo, and Kristan Temme. “Tapering off Qubits to Simulate Fermionic Hamiltonians.” arXiv, January 27, 2017. https://doi.org/10.48550/arXiv.1701.08213.
3. Setia, Kanav, Richard Chen, Julia E. Rice, Antonio Mezzacapo, Marco Pistoia, and James D. Whitfield. “Reducing Qubit Requirements for Quantum Simulations Using Molecular Point Group Symmetries.” Journal of Chemical Theory and Computation 16, no. 10 (October 13, 2020): 6091–97. https://doi.org/10.1021/acs.jctc.0c00113.

### Actual behavior

The method `qml.qchem.optimal_sector` [1,3] returns the wrong sector of [-1, -1], which delivers higher eigenvalues for the remaining 4-qubit hamiltonian:
` [-2.86259524 -2.19672513 -2.02874709 -0.69608961]`
As opposed to containing the lowest eigenvalue of the untapered hamiltonian withe the following spectrum:
```
 [-3.12541987 -3.12541987 -2.86259524 -2.64241998 -2.19672513 -2.19672513
 -2.19672513 -2.18547545 -2.18547545 -2.02874709 -1.35709798 -1.35709798
 -0.69608961 -0.17266334 -0.17266334  1.13871403]
```

**Screenshot:**
![Screenshot 2024-01-08 103146](https://github.com/PennyLaneAI/pennylane/assets/34666257/dae0e2c7-3797-4044-a1d2-a74cb27eb9a1)

#### References:

1. https://pennylane.ai/qml/demos/tutorial_qubit_tapering/
2. Bravyi, Sergey, Jay M. Gambetta, Antonio Mezzacapo, and Kristan Temme. “Tapering off Qubits to Simulate Fermionic Hamiltonians.” arXiv, January 27, 2017. https://doi.org/10.48550/arXiv.1701.08213.
3. Setia, Kanav, Richard Chen, Julia E. Rice, Antonio Mezzacapo, Marco Pistoia, and James D. Whitfield. “Reducing Qubit Requirements for Quantum Simulations Using Molecular Point Group Symmetries.” Journal of Chemical Theory and Computation 16, no. 10 (October 13, 2020): 6091–97. https://doi.org/10.1021/acs.jctc.0c00113.

### Main concern:
I found out that the implementation of the optimal sector computation in the Python package _Tangelo_ (https://github.com/goodchemistryco/Tangelo) is also incorrect, i.e., also determines the non-optimal sector of [-1, -1] automatically. For a minimal non-working Tangelo implementation see code snipped below 

Therefore, I started to have high doubts about the correctness of this entire approach of determining the optimal sector according to
_Setia, Kanav, Richard Chen, Julia E. Rice, Antonio Mezzacapo, Marco Pistoia, and James D. Whitfield. “Reducing Qubit Requirements for Quantum Simulations Using Molecular Point Group Symmetries.” Journal of Chemical Theory and Computation 16, no. 10 (October 13, 2020): 6091–97. https://doi.org/10.1021/acs.jctc.0c00113._
I am interested in investigating this concern in more details, and feel free to reach out to me to join me.

#### Note: 
I have not tried to reproduce the issue for other examples other than the HeH+ case (as in the pennylane tutorial/demo) , but since optimal_sector should be supposed to guarantee the optimal sector, to the best of my knowledge, and not rely on heuristics, this posted non-working example is sufficient to demonstrate the issue with the implementation. 

#### Tangelo implementation:
```
import numpy as np
from tangelo import SecondQuantizedMolecule
from tangelo.toolboxes.molecular_computation import IntegralSolverPsi4
from tangelo.toolboxes.qubit_mappings.mapping_transform import fermion_to_qubit_mapping
from tangelo.toolboxes.operators.operators import qubitop_to_qubitham
from tangelo.toolboxes.operators.operators import count_qubits
from openfermion.linalg import get_sparse_operator
from tangelo.toolboxes.operators.taper_qubits import QubitTapering
from tangelo.toolboxes.operators import MultiformOperator

symbols = ["He", "H"]
geometry = np.array([[0.00000000, 0.00000000, -0.87818361],
                     [0.00000000, 0.00000000,  0.87818362]])
xyz = list(zip(symbols, map(lambda x: tuple(x.tolist()), geometry)))
print(xyz)

mol = SecondQuantizedMolecule(xyz, q=+1, spin=0, solver=IntegralSolverPsi4(), frozen_orbitals=0)
qubit_h = qubitop_to_qubitham(fermion_to_qubit_mapping(mol.fermionic_hamiltonian, "jw", up_then_down=False), mapping="jw", up_then_down=False)
qubit_h_dense = get_sparse_operator(qubit_h).todense()
print("Qubits", count_qubits(qubit_h), "Terms", qubit_h.n_terms, "Constant", qubit_h.constant)
print("Eigenvalues:", np.linalg.eigvalsh(qubit_h_dense).tolist())

# ###### 🐛 BUG: Chooses incorrect sector/eigenvalues 🐛 ######
# 
# *** This leads to a higher smallest eigenvalue than for the untapered Hamiltonain ***

print("\n\nIncorrect current implementation to select correct eigenvalues for sector:")

taper = QubitTapering(qubit_h, n_qubits=4, n_electrons=2, spin=0, up_then_down=False)

taper_h = taper.z2_tapered_op
print("Tapered Hamiltonian:", taper.z2_tapered_op)
print(count_qubits(taper_h), taper_h.n_terms, taper_h.constant)
print("Sector:", taper.z2_properties["eigenvalues"])
taper_h_dense = get_sparse_operator(taper_h).todense()
print("Eigenvalues (tapered):", np.linalg.eigvalsh(taper_h_dense).tolist())

# ###### 🐛 Verify with correct optimal sector/eigenvalues 🐛 ######
# 
# *** (Manually) Choosing the eigenvalues to be -1, 1 (also applies to 1, -1) yields the matching correct smallest eigenvalue ***

print("\n\nVerify with manually chosen correct eigenvalues for sector:")

hybrid_op = MultiformOperator.from_qubitop(qubit_h, count_qubits(qubit_h))
sector = [-1, 1]
print("Sector:", sector)
taper_h = taper.z2_taper(hybrid_op, eigenvalues=sector)
taper_h_dense = get_sparse_operator(taper_h).todense()
print("Eigenvalues (tapered):", np.linalg.eigvalsh(taper_h_dense).tolist())

```

### Source code

```shell
""" 
This minimal non-working code example demonstrates the bug in the current implementation of the optimal_sector function in the qchem module of PennyLane 
and was taken from the following Pennylane tutorial/demo: https://pennylane.ai/qml/demos/tutorial_qubit_tapering/ 
"""

import pennylane as qml
from pennylane import numpy as np

symbols = ["He", "H"]
geometry = np.array([[0.00000000, 0.00000000, -0.87818361],
                     [0.00000000, 0.00000000,  0.87818362]])

H, qubits = qml.qchem.molecular_hamiltonian(symbols, geometry, charge=1)
print(H)

generators = qml.symmetry_generators(H)
paulixops = qml.paulix_ops(generators, qubits)

for idx, generator in enumerate(generators):
    print(f"generator {idx+1}: {generator}, paulix_op: {paulixops[idx]}")
    

# ###### 🐛 BUG: optimal_sector selects non-optimal sector 🐛 ######
# 
# *** This leads to a higher smallest eigenvalue than for the untapered Hamiltonain ***

print("\n\nIncorrect current implementation of optimal_sector:")

# Compute the optimal sector (incorrect current implementation!):
n_electrons = 2
paulix_sector = qml.qchem.optimal_sector(H, generators, n_electrons)
print("Optimal sector", paulix_sector)

# Apply the tapering:
H_tapered = qml.taper(H, generators, paulixops, paulix_sector)
H_tapered = qml.Hamiltonian(np.real(H_tapered.coeffs), H_tapered.ops)
print(H_tapered)

# Compute and print the eigenvalues of the original and tapered Hamiltonians:
H_sparse = qml.SparseHamiltonian(H.sparse_matrix(), wires=H.wires)
H_tapered_sparse = qml.SparseHamiltonian(H_tapered.sparse_matrix(), wires=H_tapered.wires)

print("Eigenvalues of H:\n", qml.eigvals(H_sparse, k=16))
print("\nEigenvalues of H_tapered:\n", qml.eigvals(H_tapered_sparse, k=4))


# ###### 🐛 Verify with correct optimal sector 🐛 ######
# 
# *** (Manually) Choosing the eigenvalues to be -1, 1 (also applies to 1, -1) yields the matching correct smallest eigenvalue ***

print("\n\nVerify with manually chosen correct eigenvalues for sector:")

# Manually choose correct eigenvalues instead of using optimal_sector:
n_electrons = 2
paulix_sector = [-1, 1]
print("Optimal sector", paulix_sector)

# Apply the tapering:
H_tapered = qml.taper(H, generators, paulixops, paulix_sector)
H_tapered = qml.Hamiltonian(np.real(H_tapered.coeffs), H_tapered.ops)
print(H_tapered)

# Compute and print the eigenvalues of the original and tapered Hamiltonians:
H_sparse = qml.SparseHamiltonian(H.sparse_matrix(), wires=H.wires)
H_tapered_sparse = qml.SparseHamiltonian(H_tapered.sparse_matrix(), wires=H_tapered.wires)

print("Eigenvalues of H:\n", qml.eigvals(H_sparse, k=16))
print("\nEigenvalues of H_tapered:\n", qml.eigvals(H_tapered_sparse, k=4))
```

### System information

```shell
Name: PennyLane
Version: 0.33.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/PennyLaneAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/jaeg_jn/miniconda3/envs/vqad/lib/python3.11/site-packages
Requires: appdirs, autograd, autoray, cachetools, networkx, numpy, pennylane-lightning, requests, rustworkx, scipy, semantic-version, toml, typing-extensions
Required-by: PennyLane-Lightning

Platform info:           Linux-5.15.0-83-generic-x86_64-with-glibc2.31
Python version:          3.11.6
Numpy version:           1.23.5
Scipy version:           1.9.3
Installed devices:
- default.gaussian (PennyLane-0.33.1)
- default.mixed (PennyLane-0.33.1)
- default.qubit (PennyLane-0.33.1)
- default.qubit.autograd (PennyLane-0.33.1)
- default.qubit.jax (PennyLane-0.33.1)
- default.qubit.legacy (PennyLane-0.33.1)
- default.qubit.tf (PennyLane-0.33.1)
- default.qubit.torch (PennyLane-0.33.1)
- default.qutrit (PennyLane-0.33.1)
- null.qubit (PennyLane-0.33.1)
- lightning.qubit (PennyLane-Lightning-0.33.1)
```

### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by obliviateandsurrender** [comment] 2024-01-08 17:54
Hi Jonas! Thank you for taking some time and opening this issue. 

This behaviour is not a bug but instead comes from the _second-quantized_ molecular Hamiltonian being independent of the number of electrons, i.e., it contains information regarding neutral and charged species. So, the spectrum contains energies for the species with different numbers of particles; for example, in this case, energies for `HeH` and `HeH-` are also present in the spectrum. This means that the eigenstate corresponding to the lowest eigenvalue might not have the correct particle number and, therefore, wouldn't be the correct ground state. We can see the following from the following code snippet - 

``` python
import pennylane as qml
from pennylane import numpy as np

symbols = ["He", "H"]
geometry = np.array([[0.00000000, 0.00000000, -0.87818361],
                     [0.00000000, 0.00000000,  0.87818362]])

H, qubits = qml.qchem.molecular_hamiltonian(symbols, geometry, charge=1)
num_particles = qml.qchem.Molecule(symbols, geometry, charge=1).n_electrons

eig_vals, eig_vecs = np.linalg.eigh(qml.matrix(H))
print(f"Number of Electrons: {num_particles}", f"Eigenvalues: {eig_vals}")

## output ##
# Number of Electrons: 2
# Eigenvalues: [-3.12541987 -3.12541987 -2.86259524 -2.64241998 -2.19672513 -2.19672513
#  -2.19672513 -2.18547545 -2.18547545 -2.02874709 -1.35709798 -1.35709798
#  -0.69608961 -0.17266334 -0.17266334  1.13871403]

# Building particle number operators
num_op = qml.qchem.particle_number(qubits)

print("# \t Eigenvalue \t\t #electrons")
for idx, vals in enumerate(eig_vals):
    state = eig_vecs[:, idx]
    print(idx, '\t',vals, '\t', np.round(state.T @ qml.matrix(num_op) @ state, 3).real)

## output ##
# # 	 Eigenvalue 		 #electrons
# 0 	 -3.125419874507898 	 3.0
# 1 	 -3.125419874507897 	 3.0
# 2 	 -2.8625952420684757 	 2.0
# 3 	 -2.6424199771526906 	 4.0
# 4 	 -2.1967251326448163 	 2.0
# 5 	 -2.1967251326448163 	 2.0
# 6 	 -2.1967251326448154 	 2.0
# 7 	 -2.1854754485918 	 3.0
# 8 	 -2.185475448591797 	 3.0
# 9 	 -2.028747085201344 	 2.0
# 10 	 -1.357097983358081 	 1.0
# 11 	 -1.3570979833580805 	 1.0
# 12 	 -0.6960896095131207 	 2.0
# 13 	 -0.1726633363656025 	 1.0
# 14 	 -0.17266333636560235 	 1.0
# 15 	 1.1387140262233202 	 0.0

```

From the above, we actually see that the lowest eigenvalue, `-3.12541987 Ha`, corresponds to the energy of the neutral `HeH` atom (with three electrons) instead of the cation `HeH+`, which should have two electrons (as is the case for the second lowest eigenvalue, `-2.86259524 Ha`). We have to take this into account when we find an optimal sector (via `qml.qchem.optimal_sector`) for qubit tapering, i.e., the optimal sector is the one that contains the lowest eigenvalue _with the correct particle number_ instead of the one with the _lowest eigenvalue_ (since tapering should conserve the _particle number_). 

``` python
# information needed for tapering
generators = qml.symmetry_generators(H)
paulixops = qml.paulix_ops(generators, qubits)
paulix_sector = qml.qchem.optimal_sector(H, generators, num_particles)

# tapering the Hamiltonian and getting the eigen-spectrum
H_tapered = qml.taper(H, generators, paulixops, paulix_sector)
eig_vals, eig_vecs = np.linalg.eigh(qml.matrix(H_tapered))

# taper the number operator for making it compatible with tapered subspace
num_op_tapered = qml.taper(num_op, generators, paulixops, paulix_sector) 

print("# \t Eigenvalue \t\t #electrons")
for idx, vals in enumerate(eig_vals):
    state = eig_vecs[:, idx]
    print(idx, "\t", vals, "\t", np.round(state.T @ qml.matrix(num_op_tapered) @ state, 3).real)

## output ##
# # 	 Eigenvalue 		 #electrons
# 0 	 -2.8625952420684744 	 2.0
# 1 	 -2.1967251326448127 	 2.0
# 2 	 -2.0287470852013416 	 2.0
# 3 	 -0.6960896095131203 	 2.0
```

I hope this also resolves any confusion regarding the tapering approach described in [Setia et al. (2020)](https://doi.org/10.1021/acs.jctc.0c00113).

**Comment by Jonas-Jaeger** [comment] 2024-01-10 09:18
Hi Utkarsh,
Thank you a lot for taking your time and providing such a detailed explanation. That definitely helped me out immensely. And I am happy that it is not a bug! 😄 

I can imagine although that I am not the only one who might miss this nuance in the second quantization and might get confused when reading your [pennylane qubit tapering tutorial](https://pennylane.ai/qml/demos/tutorial_qubit_tapering/) (which is great btw!). Hence, what do you think about adding a small note on that to the tutorial?

Thanks again,
Jonas

**Comment by isaacdevlugt** [comment] 2024-01-16 22:22
Hey @Jonas-Jaeger, apologies for the slow response! We're working through some higher priority PRs & issues at the moment and will get to your ticket as soon as we can 👍. I'll get in touch with you by the end of the week with an update 😄

**Comment by isaacdevlugt** [comment] 2024-01-23 22:01
Hey @Jonas-Jaeger looks like there's a PR to fix things. Once that's merged we'll close this issue :)

**Closed** 2024-01-29 23:12 UTC
Labels: bug :bug:
