### ISSUE TITLE
[BUG] operator @ hamiltonian != hamiltonian @ operator 

### ISSUE THREAD

**Issue by PhilipVinc** [PennyLaneAI/pennylane#2557] opened 2022-05-11 15:46 UTC
(I'm sorry if there's already an issue on that. I saw quite a few on `Hamiltonians`, but none looked quite like this behaviour)

Multiplying a `PauliOperator` and an `Hamiltonian` acting on different wires does not commute with multiplying `Hamiltonian` times `PauliOperator`, and leads to an error when computing expectation values. 

That's because (see example below)

- `PauliX(wire=0)@Hamiltonian(wire=1:3)`   produces `PauliZ(wires=[2]) @ <Hamiltonian: terms=2, wires=[0, 1]> `
- `Hamiltonian(wire=1:3)@PauliX(wire=0)`   produces `operator = <Hamiltonian: terms=2, wires=[0, 1, 2]>`

that's most likely because `@` is not commutative in python and favours the first operator. 

### Source code

```python
import pennylane as qml
from pennylane import numpy as np

phys_regs = 2
ancilla_regs = 1
tot_regs = phys_regs + ancilla_regs

dev = qml.device("default.qubit", wires=tot_regs)

@qml.qnode(dev)
def run(crash:bool=False):

    ops  = [qml.PauliX(i) for i in range(phys_regs)]
    coeff = [1.0 for i in ops]
    H         = qml.Hamiltonian(coeff,ops)
    
    if crash:
        operator = qml.PauliZ(wires=phys_regs) @ H
    else:
        operator = H @ qml.PauliZ(wires=phys_regs)

    print(f"{operator = }")

    return qml.expval(operator)

# this works
run(crash = False)
# prints operator = <Hamiltonian: terms=2, wires=[0, 1, 2]>


# this does not work
run(crash = True)
# prints operator = PauliZ(wires=[2]) @ <Hamiltonian: terms=2, wires=[0, 1]>
```

### Tracebacks

```shell
---------------------------------------------------------------------------
EigvalsUndefinedError                     Traceback (most recent call last)
File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/operation.py:734, in Operator.get_eigvals(self)
    733 try:
--> 734     return self.compute_eigvals(*self.parameters, **self.hyperparameters)
    735 except EigvalsUndefinedError:
    736     # By default, compute the eigenvalues from the matrix representation.
    737     # This will raise a NotImplementedError if the matrix is undefined.

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/operation.py:679, in Operator.compute_eigvals(*params, **hyperparams)
    659 r"""Eigenvalues of the operator in the computational basis (static method).
    660 
    661 If :attr:`diagonalizing_gates` are specified and implement a unitary :math:`U`,
   (...)
    677     tensor_like: eigenvalues
    678 """
--> 679 raise EigvalsUndefinedError

EigvalsUndefinedError: 

During handling of the above exception, another exception occurred:

MatrixUndefinedError                      Traceback (most recent call last)
File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/operation.py:739, in Operator.get_eigvals(self)
    738 try:
--> 739     return qml.math.linalg.eigvals(self.get_matrix())
    740 except MatrixUndefinedError as e:

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/operation.py:603, in Operator.get_matrix(self, wire_order)
    584 r"""Representation of the operator as a matrix in the computational basis.
    585 
    586 If ``wire_order`` is provided, the numerical representation considers the position of the
   (...)
    601     tensor_like: matrix representation
    602 """
--> 603 canonical_matrix = self.compute_matrix(*self.parameters, **self.hyperparameters)
    605 if wire_order is None or self.wires == Wires(wire_order):

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/operation.py:545, in Operator.compute_matrix(*params, **hyperparams)
    531 r"""Representation of the operator as a canonical matrix in the computational basis (static method).
    532 
    533 The canonical matrix is the textbook matrix representation that does not consider wires.
   (...)
    543     tensor_like: matrix representation
    544 """
--> 545 raise MatrixUndefinedError

MatrixUndefinedError: 

The above exception was the direct cause of the following exception:

EigvalsUndefinedError                     Traceback (most recent call last)
File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/_qubit_device.py:819, in QubitDevice.expval(self, observable, shot_range, bin_size)
    818 try:
--> 819     eigvals = self._asarray(observable.get_eigvals(), dtype=self.R_DTYPE)
    820 except qml.operation.EigvalsUndefinedError as e:

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/operation.py:1848, in Tensor.get_eigvals(self)
   1846             for ns_ob in g:
   1847                 # loop through all non-standard observables
-> 1848                 self._eigvals_cache = np.kron(self._eigvals_cache, ns_ob.get_eigvals())
   1850 return self._eigvals_cache

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/operation.py:741, in Operator.get_eigvals(self)
    740 except MatrixUndefinedError as e:
--> 741     raise EigvalsUndefinedError from e

EigvalsUndefinedError: 

The above exception was the direct cause of the following exception:

EigvalsUndefinedError                     Traceback (most recent call last)
Input In [38], in <module>
     24     return qml.expval(operator)
     26 run(crash = False)
---> 28 run(crash = True)

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/qnode.py:576, in QNode.__call__(self, *args, **kwargs)
    569 using_custom_cache = (
    570     hasattr(cache, "__getitem__")
    571     and hasattr(cache, "__setitem__")
    572     and hasattr(cache, "__delitem__")
    573 )
    574 self._tape_cached = using_custom_cache and self.tape.hash in cache
--> 576 res = qml.execute(
    577     [self.tape],
    578     device=self.device,
    579     gradient_fn=self.gradient_fn,
    580     interface=self.interface,
    581     gradient_kwargs=self.gradient_kwargs,
    582     override_shots=override_shots,
    583     **self.execute_kwargs,
    584 )
    586 if autograd.isinstance(res, (tuple, list)) and len(res) == 1:
    587     # If a device batch transform was applied, we need to 'unpack'
    588     # the returned tuple/list to a float.
   (...)
    595     # TODO: find a more explicit way of determining that a batch transform
    596     # was applied.
    598     res = res[0]

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/interfaces/execution.py:337, in execute(tapes, device, gradient_fn, interface, mode, gradient_kwargs, cache, cachesize, max_diff, override_shots, expand_fn, max_expansion, device_batch_transform)
    333     return batch_fn(res)
    335 if gradient_fn == "backprop" or interface is None:
    336     return batch_fn(
--> 337         qml.interfaces.cache_execute(
    338             batch_execute, cache, return_tuple=False, expand_fn=expand_fn
    339         )(tapes)
    340     )
    342 # the default execution function is batch_execute
    343 execute_fn = qml.interfaces.cache_execute(batch_execute, cache, expand_fn=expand_fn)

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/interfaces/execution.py:165, in cache_execute.<locals>.wrapper(tapes, **kwargs)
    161         return (res, []) if return_tuple else res
    163 else:
    164     # execute all unique tapes that do not exist in the cache
--> 165     res = fn(execution_tapes.values(), **kwargs)
    167 final_res = []
    169 for i, tape in enumerate(tapes):

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/interfaces/execution.py:90, in cache_execute.<locals>.fn(tapes, **kwargs)
     88 def fn(tapes, **kwargs):  # pylint: disable=function-redefined
     89     tapes = [expand_fn(tape) for tape in tapes]
---> 90     return original_fn(tapes, **kwargs)

File /usr/lib64/python3.8/contextlib.py:75, in ContextDecorator.__call__.<locals>.inner(*args, **kwds)
     72 @wraps(func)
     73 def inner(*args, **kwds):
     74     with self._recreate_cm():
---> 75         return func(*args, **kwds)

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/_qubit_device.py:332, in QubitDevice.batch_execute(self, circuits)
    327 for circuit in circuits:
    328     # we need to reset the device here, else it will
    329     # not start the next computation in the zero state
    330     self.reset()
--> 332     res = self.execute(circuit)
    333     results.append(res)
    335 if self.tracker.active:

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/_qubit_device.py:270, in QubitDevice.execute(self, circuit, **kwargs)
    267         results = qml.math.stack(results)
    269 else:
--> 270     results = self.statistics(circuit.observables)
    272 if not circuit.is_sampled:
    274     ret_types = [m.return_type for m in circuit.measurements]

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/_qubit_device.py:448, in QubitDevice.statistics(self, observables, shot_range, bin_size)
    445 for obs in observables:
    446     # Pass instances directly
    447     if obs.return_type is Expectation:
--> 448         results.append(self.expval(obs, shot_range=shot_range, bin_size=bin_size))
    450     elif obs.return_type is Variance:
    451         results.append(self.var(obs, shot_range=shot_range, bin_size=bin_size))

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/devices/default_qubit.py:540, in DefaultQubit.expval(self, observable, shot_range, bin_size)
    536         res = qml.math.squeeze(res)
    538     return qml.math.real(res)
--> 540 return super().expval(observable, shot_range=shot_range, bin_size=bin_size)

File ~/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/pennylane/_qubit_device.py:821, in QubitDevice.expval(self, observable, shot_range, bin_size)
    819     eigvals = self._asarray(observable.get_eigvals(), dtype=self.R_DTYPE)
    820 except qml.operation.EigvalsUndefinedError as e:
--> 821     raise qml.operation.EigvalsUndefinedError(
    822         f"Cannot compute analytic expectations of {observable.name}."
    823     ) from e
    825 # the probability vector must be permuted to account for the permuted wire order of the observable
    826 permuted_wires = self._permute_wires(observable)

EigvalsUndefinedError: Cannot compute analytic expectations of ['PauliZ', 'Hamiltonian'].
```

### System information

```shell
Name: PennyLane
Version: 0.23.1
```
```


### Existing GitHub issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by josh146** [comment] 2022-05-11 21:01
Thanks @PhilipVinc for catching this!

**Comment by Jaybsoni** [comment] 2022-05-11 22:07
Hi @PhilipVinc, 

Nice catch! This is in fact a bug on our side. As you figured, the issue is due to the matrix multiplication operation `@`. Specifically: 

```
>>> import pennylane as qml
>>> 
>>> ops  = [qml.PauliX(i) for i in range(phys_regs)]
>>> coeff = [1.0 for i in ops]
>>> H = qml.Hamiltonian(coeff,ops)
>>>
>>> op = qml.PauliX(0) @ H 
>>> print(type(op))
<class 'pennylane.operation.Tensor'>
>>> op = H @ qml.PauliX(0)  
>>> print(op)
<class 'pennylane.ops.qubit.hamiltonian.Hamiltonian'>
```

In the failing case, we are using the tensor multiplication defined for a general `Observable` type (which yields the `Tensor` class instance you see there). In the passing case we use the tensor multiplication defined for a `Hamiltonian` type. Currently I am working on a solution which will check if the tensor product is being performed with a `Hamiltonian` type, in this case we will always default to the `Hamiltonian` tensor multiplication method. I will let you know once the fix is released!

Thanks!

**Comment by Jaybsoni** [comment] 2022-05-12 19:14
Hi @PhilipVinc, 

I have opened a PR to address the change. Just waiting on some code review and it should be good to go 👍🏼 
https://github.com/PennyLaneAI/pennylane/pull/2570

**Comment by Jaybsoni** [comment] 2022-05-13 14:43
Hi @PhilipVinc, 

The PR has been merged, this should be fixed with the master branch of PennyLane. 
Thanks ,

**Closed by Jaybsoni** 2022-05-13 14:43 UTC
Labels: bug :bug:
